name: Python Tests and Deploy

# Trigger the workflow on pushes and pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run tests with unittest
      - name: Run tests
        run: python -m unittest discover -s tests -p "add_test.py"

  deploy:
    runs-on: ubuntu-latest
    needs: test   # This makes sure the deploy job only runs if the test job succeeds

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Example deployment step (customize based on your deployment needs)
      - name: Deploy application
        run: |
          echo "Starting deployment..."
          echo "Deployment complete!"
